name: smart_fridge
description: Умный холодильник — инвентаризация продуктов дома
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Состояние
  provider: ^6.1.2

  # База данных
  sqflite: ^2.3.3
  path: ^1.9.0

  # Сеть
  http: ^1.2.1

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  # Локальное хранение
  shared_preferences: ^2.3.2

  # Сканер штрихкода
  mobile_scanner: ^5.2.3

  # Уведомления
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4

  # UI
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/